### ISSUE TITLE
When deleting a project an error message appears

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/intellij-openshift-connector#632] opened 2023-12-01 12:06 UTC
When deleting a project, instead of automatically switching to an older project or showing the default message when no older project is available, this error message is show:

Could not get namespaces: The okhttp client executor has been shutdown.  More than likely this is because the KubernetesClient.close method (see debug logging) has been called - please ensure that is intentional. Dispatcher: okhttp3.Dispatcher@6dd4f708

Refreshing helps to show the correct content but does not happen automatically.

**Comment by adietish** [comment] 2024-07-03 15:13
I can't reproduce this. When I delete the current project in intellij-openshift-connector the tree is refreshed and then reports that the project is missing.

https://github.com/redhat-developer/intellij-openshift-connector/assets/25126/33ff12a0-2227-4469-8d4f-2704da6c1eac

@lgrossma what am I missing?

**Comment by adietish** [comment] 2024-07-04 09:35
@sbouchet: can you reproduce this issue? I cannot (see comment above). Thanks

**Comment by sbouchet** [comment] 2024-07-08 13:55
i can't reproduce either, even with old or with #862 fix using oc. the old project is shown but the children is now the message telling the project isn't available, informing the user to choose/create another one. 
closing.

**Closed by sbouchet** 2024-07-08 13:55 UTC
Labels: bug, severity/minor

**Comment by martinszuc** [comment] 2024-07-08 14:40
I cannot reproduce this either. For me behaves always like described in https://github.com/redhat-developer/intellij-openshift-connector/issues/632#issuecomment-2214146594.
