### ISSUE TITLE
Helm chart installation and cluster project selection 

### ISSUE THREAD

**Issue by martinszuc** [redhat-developer/intellij-openshift-connector#612] opened 2023-11-09 20:21 UTC
related to: #676, #661, #613 
[kind/bug]

## What versions of software are you using?
- Operating System: Fedora 38
- IntelliJ version: 2023.2 Ultimate
- OpenShift version: 1.7.0 SNAPSHOT

## What i did to encounter this: 
Already logged in to cluster, I created "my-test-2" cluster project next to original "my-test". The project name in the tree does not refresh. (needs restart (most likely [this issue):](https://github.com/redhat-developer/intellij-openshift-connector/issues/595) 
![01-create-new-project-on-cluster](https://github.com/redhat-developer/intellij-openshift-connector/assets/100486753/595ed784-9c60-41a2-89e6-b174538d487b)

Here things branch out according to the fact if we restart intellij or not:

IF WE DONT: there is behavior when we install helm chart on this unrefreshed tree . Here, after I created the new "my-test-2"  project, I installed the mysql helm chart and in the background you can see openshift console get updated  configs with the helm release but under the "my-test-2" project, when the tree says "my-test" which is the original project. I guess this is correct if the tree refresh would get fixed.
![02-installing-helm-chart-on-new-project](https://github.com/redhat-developer/intellij-openshift-connector/assets/100486753/58df490a-d108-4168-9b26-a038677f817f)

 IF WE RESTART IDE: 
Tree is properly refreshed. But when I delete the project the tree refreshes itself but with  "Failed to load chart releases".:
![03-removing-already-restarted-2-projects](https://github.com/redhat-developer/intellij-openshift-connector/assets/100486753/d906bec7-e383-4bcb-aad5-7f6cea0458fd)

When i tried to install helm chart on project with the  "Failed to load chart releases". It threw error: 
![2023-11-09-20-55-08](https://github.com/redhat-developer/intellij-openshift-connector/assets/100486753/80d9abc4-14d6-4f45-86cd-f09aa1652fba)

> Process exited with an error: 1 (Exit value: 1) Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource Secret "mysql" in namespace "my-test-2": secrets "mysql" is forbidden: User "developer" cannot get resource "secrets" in API group "" in the namespace "my-test-2":

## Expected behavior 

Should helm charts get installed under a project or cluster? In that case the button "Open helm charts" is in incorrect place. 
Otherwise there is a question if the user / dev should be able to switch between projects within cluster. And be able to do this within IDE.

**Comment by adietish** [comment] 2024-01-25 15:16
The bug where the tree won't refreshing when creating a new project is gone. 

**Steps:**
1. ASSERT: be logged into openshift cluster (works also with minikube)
2. EXEC: pick "New Project" in ctx menu to the cluster, provide name and confirm

**Result:**
The resource tree is refreshed and is using the new project as current/active project

**Comment by adietish** [comment] 2024-01-26 10:52
I can reproduce issue 2:

**Steps:**
1. EXEC: create a new project (ex. test7)
2. EXEC: delete the new project

**Result:**
<img width="484" alt="image" src="https://github.com/redhat-developer/intellij-openshift-connector/assets/25126/ec536348-e453-4a43-acc4-c181aa67cf4d">
The tree is refreshed but it is displaying the deleted project.

**Comment by adietish** [comment] 2024-01-26 13:22
I see how this is annoying to the user. Displaying a different project instead of the missing one isn't helpful either: the tree would not unveil to the user that kube config points to a missing project. We would therefore have to change the current project in kube config, which is unexpected, too.
@martinszuc, @sbouchet, @vrubezhny: thoughts?

**Comment by adietish** [comment] 2024-01-26 14:39
> Should helm charts get installed under a project or cluster? In that case the button "Open helm charts" is in incorrect place.

I fully agree on this one and raised already. Helm charts are installed into the current project. I came to the same conclusion that this wasn't clear and thus filed #613
The latest implementation in vscode has it on the Helm node
<img width="557" alt="image" src="https://github.com/redhat-developer/intellij-openshift-connector/assets/25126/037052e3-1d39-4579-b3b5-47f1bfd2130d">
We dont have a helm node with the repositories yet. I'd move the command to the namespace/project node for now: #676

> Otherwise there is a question if the user / dev should be able to switch between projects within cluster. And be able to do this within IDE.

Fully agree on this one, too. I filed & implemented #661

**Comment by datho7561** [comment] 2024-01-26 15:53
> The latest implementation in vscode has it on the Helm node

We also have it as a context menu item on the project. I think we should move the "Helm" node to a different section since it's mostly used for listing and configuring Helm repos, which can be done even if you aren't connected to a cluster. If we move the "Helm" node, we should also remove the "Open Helm View" context menu item.

> oc also behaves in this way: if you delete the current project, kube config stays unaltered, it still points to project that was deleted.

If you can replicate the VS Code behaviour of a node with an error icon and text that says "missing project", I think that would be the best method.

**Comment by adietish** [comment] 2024-01-30 13:50
The issue here where the tree isn't refreshed when a project is deleted doesnt occurr any more. All related improvements/issues were filed to separate issues.
Closing.

**Closed by adietish** 2024-01-30 13:50 UTC
Labels: bug
